### ISSUE TITLE
fluentd with es plugin failing to send data to elasticsearch

### ISSUE THREAD

**Issue by harikum** [uken/fluent-plugin-elasticsearch#458]
#### Problem
fluentd with es plugin failing to send data to elasticsearch

fluentd tails the running log file (in json format), fluentd container has access to the files and can read the log file

docker logs of the fluentd docker container does report processing of the lines (tail), however the parsed data does not show up in kibana. Kibana only reports fluent.info logs with startup/shutdown of fluent worker.

It looks to me like the elasticsearch plugin is unable match any tags to copy/forward to ES.

#### Steps to replicate
can replicate at will with the existing config and versions.

#### Expected Behavior or What you need to ask

the file processed by fluentd using the tail plugin, is expected to be forawrded into ES and available in kibana for searching.

fluentd tails the running log file (in json format), fluentd container has access to the files, can read the log file

fluentd container logs reports the processing of the lines (tail), however the parsed data its NOT avaialble in kibana.
only fluent.info logs with startup/shutdown of fluent worker is getting registered.

looks to me like the elasticsearch plugin is unable match any tag to forward to ES.

#### Using Fluentd and ES plugin versions

Environment: Elasticsearch, Fluentd, Kibana running as Docker containers on the same host
host: RHEL 7.3 VM
fluentd:v0.12.43-debian
fluent-plugin-elasticsearch: 1.9.2
ES/Kibana: v6.2.4 (have tried different versions including oss, same result)

Config files 
## fluent.conf

```aconf
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<source>
  @type tail
  path /falco/falco.out
  pos_file /falco/falco.out.pos
  tag falcologs
  read_from_head true
  format json
  <format>
    @type json
  </format>
</source>

<match **>
  @type copy
  <store>
    @type elasticsearch
    host ES_HOST
    port 9200
    index_name fluentd
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    flush_interval 15s
  </store>
  <store>
    @type stdout
  </store>
</match>
```

## docker deployment.yaml

```yaml
version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./falco:/falco
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    ports:
      - "9200:9200"
  kibana:
    image: kibana
    environment:
      - ELASTICSEARCH_URL=http://ES_HOST:9200
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
```

## fluentd Dockerfile

```dockerfile
FROM fluent/fluentd:v0.12.43-debian
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-rdoc", "--no-ri", "--version", "1.9.2"]
```
