### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406]

### ISSUE THREAD

**Issue by nbenjamin** [uken/fluent-plugin-elasticsearch#552]
#### Problem
fluentd_1        | 2019-02-25 21:12:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-02-25 21:12:24 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:3faa23644080"
fluentd_1        |   2019-02-25 21:12:22 +0000 [warn]: suppressed same stacktrace
fluentd_1        | 2019-02-25 21:12:22 +0000 fluent.warn: {"next_retry":"2019-02-25 21:12:24 +0000","error_class":"Elasticsearch::Transport::Transport::Errors::NotAcceptable","error":"[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}","plugin_id":"object:3faa23644080","message":"temporarily failed to flush the buffer. next_retry=2019-02-25 21:12:24 +0000 error_class=\"Elasticsearch::Transport::Transport::Errors::NotAcceptable\" error=\"[406] {\\\"error\\\":\\\"Content-Type header [] is not supported\\\",\\\"status\\\":406}\" plugin_id=\"object:3faa23644080\""}
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

Using the following configuration to spin up locally, fluentd, kibana and elastic search
```yaml
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.5.4
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.5.4
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
```

fluent.conf
```properties
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match *.**>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    flush_interval 1s
  </store>
  <store>
    @type stdout
  </store>
</match>

```

"fluent-plugin-elasticsearch"  => "version", "1.9.5"
