### ISSUE TITLE
Self-signed Certificate verify failed (Fluend + Open Distro for Elasticsearch)

### ISSUE THREAD

**Issue by RufusDerrid** [uken/fluent-plugin-elasticsearch#597]
#### Problem

Fluend trying connect to ODFE by https and getting error:
```
`#0 unexpected error error_class=Faraday::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized: 
`Excon.defaults[:ssl_ca_path] = path_to_certs` `ENV['SSL_CERT_DIR'] = path_to_certs`
`Excon.defaults[:ssl_ca_file] = path_to_file`
`ENV['SSL_CERT_FILE'] = path_to_file`
`Excon.defaults[:ssl_verify_callback] = callback`
(see OpenSSL::SSL::SSLContext#verify_callback)
`Excon.defaults[:ssl_verify_peer] = false` (less secure)."
```

#### Steps to replicate

1. Create directory certs and generate certificates:
```
//Root CA
openssl genrsa -out root-ca-key.pem 2048
openssl req -new -x509 -sha256 -key root-ca-key.pem -out root-ca.pem
//Fluentd cert
openssl genrsa -out fluentd-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in fluentd-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out fluentd-key.pem
openssl req -new -key fluentd-key.pem -out fluentd.csr
openssl x509 -req -in fluentd.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out fluentd.pem
//Node cert
openssl genrsa -out odfe-node1-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in odfe-node1-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out odfe-node1-key.pem
openssl req -new -key odfe-node1-key.pem -out odfe-node1.csr
openssl x509 -req -in odfe-node1.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out odfe-node1.pem
```
2. Create custom-elasticsearch.yml:
```
opendistro_security.ssl.transport.pemcert_filepath: odfe-node1.pem
opendistro_security.ssl.transport.pemkey_filepath: odfe-node1-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: odfe-node1.pem
opendistro_security.ssl.http.pemkey_filepath: odfe-node1-key.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.authcz.admin_dn:
  - 'CN=test,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'
opendistro_security.nodes_dn:
  - 'CN=odfe-node1,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'

opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.config.disabled_transport_categories: NONE
```
3. Create fluent.conf:
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match *.**>
    @type copy
    <store>
      @type elasticsearch
      scheme https
      host odfe-node1
      port 9200
      ssl_version TLSv1_2
      ca_file /fluentd/certs/root-ca.pem
      client_cert /fluentd/certs/fluentd.pem
      client_key /fluentd/certs/fluentd-key.pem
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y%m%d
      include_tag_key true
      type_name access_log
      tag_key @log_name
      flush_interval 1s
    </store>
    <store>
      @type stdout
  </store>
</match>
```
4. Create custom-fluentd image from Dockerfile:
```
FROM fluent/fluentd:v1.5-1

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent
```
6. Up docker-compose.yml:
```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo Security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./certs/odfe-node1.pem:/usr/share/elasticsearch/config/odfe-node1.pem
      - ./certs/odfe-node1-key.pem:/usr/share/elasticsearch/config/odfe-node1-key.pem
      - ./certs/fluentd.pem:/usr/share/elasticsearch/config/fluentd.pem
      - ./certs/fluentd-key.pem:/usr/share/elasticsearch/config/fluentd-key.pem
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
      
  fluentd:
    image: custom-fluentd
    ports:
      - "24224:24224"
    environment:
      - "SSL_CERT_DIR=/fluentd/certs"
      - "SSL_CERT_FILE=/fluentd/certs/root-ca.pem"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./certs:/fluentd/certs
    networks:
      - odfe-net

volumes:
  odfe-data1:

networks:
  odfe-net:
```

#### Using Fluentd and ES plugin versions

* OS version: Ubuntu 16.04.5 LTS
* Docker Composer
* Fluentd v1.5-1
* Open Distro for Elasticsearch 0.9.0
