### ISSUE TITLE
Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.

### ISSUE THREAD

**Issue by tirelibirefe** [uken/fluent-plugin-elasticsearch#776]
#### Problem

`[warn]: #0 [elasticsearch] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.`

I haven't changed many things but I am not sure my config is correct or not. Actually there is no any sample reference for Fluentd Helm ElasticSearch configuration. 

My ElasticSearch works normally. My ElasticSearch uses custom tls certificate which is in es-tls.

```
I am trying to install Fluentd on my Kubernetes but it can never connect to ElasticSearch

#### Steps to replicate
bash-5.0# curl -u "elastic:636ByujI053Pl3Zu5E0ZsnG6" -k "https://escluster-es-http.elastic-system.svc.cluster.local:9200" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   546  100   546    0     0   7280      0 --:--:-- --:--:-- --:--:--  7280
{
  "name": "escluster-es-default-0",
  "cluster_name": "escluster",
  "cluster_uuid": "0XnwElYuQICbi-QELvNjsw",
  "version": {
    "number": "7.8.0",
    "build_flavor": "default",
    "build_type": "docker",
    "build_hash": "757314695644ea9a1dc2fecd26d1a43856725e65",
    "build_date": "2020-06-14T19:35:50.234439Z",
    "build_snapshot": false,
    "lucene_version": "8.5.1",
    "minimum_wire_compatibility_version": "6.8.0",
    "minimum_index_compatibility_version": "6.0.0-beta1"
  },
  "tagline": "You Know, for Search"
}
bash-5.0#
```
**OR**

Provide example config and message

```
output:
  host: escluster-es-http.elastic-system.svc.cluster.local
  port: 9200
  scheme: https
  sslVersion: TLSv1_2
  buffer_chunk_limit: 2M
  buffer_queue_limit: 8

env: {}

extraEnvVars:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: escluster-es-elastic-user
        key: elastic
extraVolumes:
  - name: es-certs
    secret:
      defaultMode: 420
      secretName: es-tls
extraVolumeMounts:
  - name: es-certs
    mountPath: /certs
    readOnly: true
```

#### Expected Behavior or What you need to ask

I expect Fluentd can connect ElasticSearch.

#### Using Fluentd and ES plugin versions

* OS version 
* Bare Metal or within Docker or Kubernetes or others? BareMetal Kubernetes 1.18
* Fluentd v0.12 or v0.14/v1.0 v1.10
  * paste result of ``fluentd --version`` or ``td-agent --version`` v1.10 the latest one
* ES plugin 3.x.y/2.x.y or 1.x.y I'm not using any custom plugin.
  * paste boot log of fluentd or td-agent fluentd
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock nogemlock
* ES version (optional) 7.8
* ES template(s) (optional no template)
