### ISSUE TITLE
Custom elasticsearch index template is not getting created

### ISSUE THREAD

**Issue by harshavardhanc** [uken/fluent-plugin-elasticsearch#813]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I'm trying to create custom elasticsearch template for fluentd index but it is not creating the template in elasticsearch, I had gone through this [issue](https://github.com/uken/fluent-plugin-elasticsearch/issues/33) and also the [implementation](https://github.com/uken/fluent-plugin-elasticsearch/pull/194) 

#### Steps to replicate

Steps: 
1. Created index template json file as configMap and did volume mount.
2. Added _template_name_ and _template_file_ as env and updated the path and template name.

**OR**

Changes are done here:  
https://github.com/project-sunbird/sunbird-devops/blob/fluentd/kubernetes/helm_charts/logging/fluentd-elasticsearch/values.yaml
https://github.com/project-sunbird/sunbird-devops/blob/fluentd/kubernetes/helm_charts/logging/fluentd-elasticsearch/templates/daemonset.yaml

Note: configMap is created manually
Provide example config and message

#### Expected Behavior or What you need to ask

I want create the fluentd index with replica 0, for that I'm trying to test with custom template. 
Anything that I'm doing wrong here, please help.

#### Using Fluentd and ES plugin versions

* Running in Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  * fluentd 1.9.3
* ES plugin 3.x.y/2.x.y or 1.x.y
```activesupport (6.0.2.2)
addressable (2.7.0)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bundler (default: 2.1.4)
cgi (default: 0.1.0)
concurrent-ruby (1.1.6)
cool.io (1.6.0)
csv (default: 3.1.2)
date (default: 3.0.0)
dbm (default: 1.1.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
domain_name (0.5.20190701)
elasticsearch (7.6.0)
elasticsearch-api (7.6.0)
elasticsearch-transport (7.6.0)
etc (default: 1.1.0)
excon (0.73.0)
faraday (1.0.1)
fcntl (default: 1.0.0)
ffi (1.12.2)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.13)
fluent-plugin-elasticsearch (4.0.7)
fluent-plugin-kubernetes_metadata_filter (2.4.5)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.7.3)
fluent-plugin-systemd (1.0.2)
fluentd (1.9.3)
forwardable (default: 1.3.1)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.0)
http (4.4.1)
http-accept (1.7.0)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.1)
http_parser.rb (0.6.0)
i18n (1.8.2)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.3)
json (default: 2.3.0)
kubeclient (4.6.0)
logger (default: 1.4.2)
lru_redux (1.1.0)
matrix (default: 0.2.0)
mime-types (3.3.1)
mime-types-data (3.2019.1009)
minitest (5.14.0, 5.13.0)
msgpack (1.3.3)
multi_json (1.14.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
observer (default: 0.1.0)
oj (3.10.5)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
ostruct (default: 0.2.0)
power_assert (1.1.7)
prime (default: 0.1.1)
prometheus-client (0.9.0)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.4)
quantile (0.2.1)
racc (default: 1.4.16)
rake (13.0.1)
rdoc (default: 6.2.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
recursive-open-struct (1.1.1)
reline (default: 0.1.3)
rest-client (2.1.0)
rexml (default: 3.2.3)
rss (default: 0.2.8)
sdbm (default: 1.0.0)
serverengine (2.2.1)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strptime (0.2.3)
strscan (default: 1.0.3)
systemd-journal (1.3.3)
test-unit (3.3.4)
thread_safe (0.3.6)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (1.2.7)
tzinfo-data (1.2019.3)
unf (0.1.4)
unf_ext (0.0.7.7)
uri (default: 0.10.0)
webrick (default: 1.6.0)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
yaml (default: 0.1.0)
zeitwerk (2.3.0)
zlib (default: 1.1.0)
```
* ES version : 6.8.x
* ES template: 
```
{
  "template": "te*",
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "string",
          "index": "not_analyzed"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
```

**Comment by cosmo0920** [comment]
First, we don't actively handle custom helm charts question in this issue tracker.
Using custom helm charts should be used at your own risk.
 
My k8s fluentd daemonset for Elasticsearch output can handle template file as ConfigMap as follows:

```yaml
apiVersion: v1
data:
  index_template.json: |-
    {
        "index_patterns": [
            "logstash-default*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "3"
            }
        }
    }
kind: ConfigMap
metadata:
  name: es-template
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-master.default.svc"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "true"
          # Option to configure elasticsearch plugin with tls
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: "TLSv1_2"
          # X-Pack Authentication
          # =====================
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "changeme"
          # Logz.io Authentication
          # ======================
          - name: LOGZIO_TOKEN
            value: "ThisIsASuperLongToken"
          - name: LOGZIO_LOGTYPE
            value: "kubernetes"
          # ILM parameters
          # ==============
          - name: FLUENT_ELASTICSEARCH_ENABLE_ILM
            value: "true"
          - name: FLUENT_ELASTICSEARCH_TEMPLATE_FILE
            value: /host/index_template.json
          - name: FLUENT_ELASTICSEARCH_TEMPLATE_NAME
            value: "logstash-default"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: es-template
          mountPath: /host
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: es-template
        configMap:
          name: es-template
```

Our maintaining fluent-debian-elasticsearch image is here:
https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.11/debian-elasticsearch7
